# schemes: https://github.com/chriskempson/base16-schemes-source.git
schemes: https://github.com/base16-project/base16-schemes.git
templates: https://github.com/chriskempson/base16-templates-source.git
